version: "3.9"

services:
  app:
    container_name: app
    image: "shopping-cart-api:1.0.0"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - dbapp
    restart: on-failure

  dbapp:
    container_name: dbapp
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
    restart: on-failure
